# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('published_at', models.DateTimeField(verbose_name='公開日時')),
                ('source_url', models.URLField(verbose_name='元記事URL')),
                ('audio_url', models.URLField(verbose_name='音声データURL')),
                ('is_published', models.BooleanField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
